version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=photo_admin
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=Passw0rd
      - PHOTO_DIR=/app/photos
    volumes:
      - ./photos:/app/photos
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=photo_admin
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=Passw0rd
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 