version: '3.8'

services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    command: >
      sh -c "npm install &&
             npm run dev &
             python app.py" 